### ISSUE TITLE
Figure out new function list

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/hazardItems#17]
- [x] addLayer
- [x] template
- [ ] modifyItem
- [ ] getLayer(ID, field = NULL)
- [ ] getTemplateItem(ID, field = NULL)

**Comment by jiwalker-usgs** [comment]
Working on add_layer

**Comment by jiwalker-usgs** [comment]
May need some fixing, but add_layer done

**Comment by jiwalker-usgs** [comment]
crossing off template, though some helpers to create the item list are probably necessary

**Comment by ldecicco-USGS** [comment]
woah! nice list

**Comment by jiwalker-usgs** [comment]
getTemplateItem(field="children") returns character vector of item ids.  Should call /data/template/item/{id} to get this

**Comment by jread-usgs** [comment]
Working on `getTemplateItem(field="chillin's")`

**Comment by jread-usgs** [comment]
@jiwalker-usgs if I hit item CAQw7M1 on dev w/ a GET, I get a 405. But, if I use data/item/ instead, I get the item. Probably need to talk quick on this.

**Comment by jiwalker-usgs** [comment]
Closing as done.
