### ISSUE TITLE
create workflow vignette

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/hazardItems#43]

**Comment by jread-usgs** [comment]
@ldecicco-USGS it would be great to get some tips on how you made that html vignette.

**Comment by ldecicco-USGS** [comment]
https://raw.githubusercontent.com/ldecicco-USGS/EGRETci/master/vignettes/EGRETci.Rmd

**Comment by ldecicco-USGS** [comment]
Need something like this on top:

```
---
title: "Introduction to EGRET Confidence Intervals"
author: "Robert M. Hirsch, Laura A. De Cicco"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction to EGRET Confidence Intervals}
  \usepackage[utf8]{inputenc}
---
```

**Comment by ldecicco-USGS** [comment]
then
```r
devtools::build_vignettes()
```
and violia!

**Comment by jread-usgs** [comment]
great, thanks!

**Comment by jread-usgs** [comment]
first, create top level folder for "vignettes"
then in RStudio, "file -> new file -> R markdown
then see what @ldecicco-USGS did and try to follow the pattern/concepts

**Comment by jread-usgs** [comment]
how is this going @mhines-usgs ?

**Comment by jread-usgs** [comment]
This is looking pretty good. One section I think we are missing right up at the top is "Installing `hazardItems` package"

**Comment by mhines-usgs** [comment]
knittin' it in now.

**Comment by jread-usgs** [comment]
:cake:

**Comment by mhines-usgs** [comment]
knitted a few more bits in

**Comment by mhines-usgs** [comment]
i like mapdata so much i installed twice. fixin.

**Comment by mhines-usgs** [comment]
Will continue to refine as we nail down publishStorm and supporting functions.
