### ISSUE TITLE
create "publishStorm()"

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/hazardItems#49]
this is a handler for initial publish and update. Completely abstracts most of the filtering and assumes that all supported attrs in the shapefile will be published or updated.

**Comment by jread-usgs** [comment]
see vignette for clarification of workflow and use case

**Comment by jread-usgs** [comment]
@mhines-usgs and @jiwalker-usgs this sounded great on Friday, but now I am wondering how this wrapper deals with auth. Any ideas on that?

**Comment by jiwalker-usgs** [comment]
ooh, that's a tough one.  I was thinking too, and writing a cross-platform wrapper would suck as well.  So maybe just a one liner in R that abstracts out all the messy logic of the items list.

**Comment by mhines-usgs** [comment]
Closing this. Updates still occurring on the function, but overall this issue is complete.
