### ISSUE TITLE
incorporate cache refresh

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/hazardItems#53]
- [x] download cache
- [x] tile cache
- [x] item cache (metadata)
- [x] thumbnail regen

**Comment by mhines-usgs** [comment]
yes, and because if we're going to be replacing/substituting the children, this will need to auto-occur, just like the thumbnail generation/regeneration...

**Comment by jread-usgs** [comment]
part of this is implemented w/ @jiwalker-usgs 's `deleteDownload` function, and the `downloadItem` that he just checked in.

**Comment by jread-usgs** [comment]
@jiwalker-usgs any way to deal with the tile cache delete from R?

**Comment by jiwalker-usgs** [comment]
No, that cache was built rather hastily and has no real good way of dealing with it outside of clobbering the whole thing.

**Comment by jread-usgs** [comment]
research item: figure if we can POST to thumbnail service

**Comment by jread-usgs** [comment]
tile cache is awaiting cache DELETE service by @jiwalker-usgs and thumbnail is included on #67 

What is tile cache metadata?

**Comment by jread-usgs** [comment]
@jiwalker-usgs can you clarify "item cache (metadata)" ?

**Comment by jread-usgs** [comment]
Still need to discuss w/ @jiwalker-usgs on the item structure cache, which I think is part of this https://trello.com/c/P2twPmWs
