### ISSUE TITLE
set package base_url back to http

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/hazardItems#64]
And use separate base_url for all https traffic. fun fun. This is the result of the http switch, and @mhines-usgs tracked this down

**Comment by jread-usgs** [comment]
@mhines-usgs I will do this and send a PR for you to review.

**Comment by mhines-usgs** [comment]
:+1:

**Comment by jread-usgs** [comment]
ok, after discussion w/ @jiwalker-usgs, https is actually supported and as long as prod points to `https://cida.usgs.gov/coastalchangehazardsportal/`, we should be good. Changing now.
