### ISSUE TITLE
add deleteTileCache function

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/hazardItems#70]
will require some discussion w/ @jiwalker-usgs 

@mhines-usgs you up for leading this?

**Comment by jread-usgs** [comment]
@mhines-usgs I am going to work on this, but feel free to contribute if you want while traveling :)

**Comment by mhines-usgs** [comment]
@jread-usgs Thanks, I could do that, if you might stub out the thoughts for me. Or other issues, truly.
