### ISSUE TITLE
Create itemExists check function

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/hazardItems#71]

**Comment by mhines-usgs** [comment]
https://github.com/USGS-R/hazardItems/pull/73

**Comment by jread-usgs** [comment]
Can we add two tests (one for an item that exists and one for one that doesn't) for this?

**Comment by mhines-usgs** [comment]
added in tests, removing unnecessary bits. waiting for coveralls. https://github.com/USGS-R/hazardItems/pull/75
