### ISSUE TITLE
sysdata.rda not loaded with library()

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-R/hazardItems#81]
The WPS4R iem.summary algorithm depends on sysdata.rda being loaded.  This was moved from data and is no longer in the environment.

**Comment by jread-usgs** [comment]
Yes, this is local to the package. I can help w/ this.

**Comment by jread-usgs** [comment]
I can create a function that exports this. `attrmap` is needed by WPS4R. @jiwalker-usgs can you link to the code in the other repo for this so I can test it?

**Comment by jiwalker-usgs** [comment]
@jread-usgs https://github.com/USGS-CIDA/coastal-hazards/blob/master/coastal-hazards-n52/src/main/webapp/R/r_scripts/item.summary.R

**Comment by jread-usgs** [comment]
trying this w/ https://github.com/USGS-CIDA/coastal-hazards/commit/1b836f2879fb367e536ba97971667f9d532587a6
